#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config focus_follows_mouse autoraise
#yabai -m config mouse_follows_focus on
yabai -m config mouse_drop_action            swap

yabai -m config window_opacity               off
yabai -m config window_border                off
yabai -m config auto_balance                 off

yabai -m config window_topmost on
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_shadow                on
yabai -m config split_ratio                  0.50

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  06
yabai -m config bottom_padding               06
yabai -m config left_padding                 06
yabai -m config right_padding                06
yabai -m config window_gap                   06
yabai -m config native-fullscreen            on
yabai -m config external_bar main:26:0

# rules
yabai -m rule --add app="^System Preferences$" layer=above layer=above manage=off
yabai -m rule --add app="^RuneLite$" layer=above manage=off
yabai -m rule --add app="^Finder$" layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^Karabiner.*$" layer=above manage=off
yabai -m rule --add app="^Keyboard Setup Assistant$" layer=above manage=off
yabai -m rule --add app="^Calculator$" layer=above manage=off

#yabai -m signal --add event=space_changed action="osascript -e 'tell application id \"Übersicht\" to refresh widget id \"simple-bar-index-jsx\"'"
#yabai -m signal --add event=display_changed action="osascript -e 'tell application id \"Übersicht\" to refresh widget id \"simple-bar-index-jsx\"'"
#yabai -m signal --add event=window_resized action="osascript -e 'tell application id \"Übersicht\" to refresh widget id \"simple-bar-index-jsx\"'"
#yabai -m signal --add event=window_focused action="osascript -e 'tell application id \"Übersicht\" to refresh widget id \"simple-bar-index-jsx\"'"
#yabai -m signal --add event=application_front_switched action="osascript -e 'tell application id \"Übersicht\" to refresh widget id \"simple-bar-index-jsx\"'"
#yabai -m signal --add event=window_destroyed action="osascript -e 'tell application id \"Übersicht\" to refresh widget id \"simple-bar-index-jsx\"'"

echo "yabai loaded"
