# Comments
"comment" = { fg = "white", modifiers = ["italic"] }

# Constants
"constant" = "orange"
"constant.boolean" = "maroon"
"constant.character" = "teal"
"constant.numeric" = "orange"
"constant.macro" = "orange"

# Strings
"string" = "green"

# Keywords
"keyword" = "purple"
"keyword.control.exception" = "magenta"
"keyword.directive" = "pink"
"keyword.import" = "purple"
"keyword.return" = "purple"

# Operators
"operator" = "sky"

# Functions, Methods, Macros
"function" = "blue"
"function.macro" = "orange"

# Types
"type" = "yellow"
"type.enum" = "yellow"
"type.enum.variant" = "orange"

# Constructors
"constructor" = "blue"

# Variables
"variable" = "white"
"variable.parameter" = { fg = "maroon", modifiers = ["italic"] }
"variable.other.member" = "light_blue"
"variable.builtin" = "teal"

# Labels & Namespaces
"label" = "light_blue"
"namespace" = "light_blue"

# Special / Misc
"special" = "beige"
"punctuation" = "white"
"punctuation.special" = "beige"

# Tags
"tag" = { fg = "light_blue", modifiers = ["bold"] }

# Markup
"markup.heading.1" = "red"
"markup.heading.2" = "yellow"
"markup.heading.3" = "blue"
"markup.heading.4" = "orange"
"markup.heading.5" = "green"
"markup.heading.6" = "purple"

"markup.bold" = { fg = "maroon", modifiers = ["bold"] }
"markup.italic" = { fg = "maroon", modifiers = ["italic"] }
"markup.strikethrough" = { fg = "white", modifiers = ["crossed_out"] }
"markup.quote" = { fg = "maroon", modifiers = ["bold"] }
"markup.raw" = "teal"

"markup.link.url" = { fg = "beige", modifiers = ["italic", "underlined"] }
"markup.link.label" = "light_blue"
"markup.link.text" = { fg = "beige" }

"markup.list.checked" = "green"
"markup.list.unchecked" = "white"

# Diff
"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "yellow"

############################################
# Diagnostics & Gutter Indicators
############################################
error = "red"
warning = "yellow"
info = "sky"
hint = "teal"

"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.info" = { underline = { color = "sky", style = "curl" } }
"diagnostic.hint" = { underline = { color = "teal", style = "curl" } }

"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { fg = "yellow", modifiers = ["dim"] }

############################################
# User Interface
############################################

# Main Editor & Text
"ui.background" = { fg = "white", bg = "background" }
"ui.text" = "white"

# Window Splits, Help Windows
"ui.window" = { fg = "white", bg = "background" }
"ui.help" = { fg = "white", bg = "float_background" }

# Popups (documentation / floating)
"ui.popup" = { fg = "white", bg = "float_background" }

# Menu (autocomplete)
"ui.menu" = { fg = "white", bg = "surface0" }
"ui.menu.selected" = { fg = "white", bg = "surface1", modifiers = ["bold"] }

# Picker (fuzzy finder)
"ui.picker.header" = { fg = "white", bg = "float_background" }
"ui.picker.header.column" = { fg = "sky", bg = "float_background" }
"ui.picker.header.column.active" = { fg = "light_blue", bg = "float_background" }

# Gutter / Line Numbers
"ui.gutter" = { fg = "surface2" }
"ui.gutter.selected" = { fg = "beige" }
"ui.linenr" = { fg = "surface2" }
"ui.linenr.selected" = { fg = "beige" }

# Cursor
"ui.cursor" = { fg = "background", bg = "white" }
"ui.cursor.match" = { fg = "background", bg = "maroon" }

# Statusline
"ui.statusline" = { fg = "white", bg = "results_background" }
"ui.statusline.inactive" = { fg = "surface2", bg = "results_background" }
"ui.statusline.normal" = { fg = "background", bg = "blue"  }
"ui.statusline.insert" = { fg = "background", bg = "green"  }
"ui.statusline.select" = { fg = "background", bg = "purple"  }

# Bufferline
"ui.bufferline" = { fg = "white", bg = "surface0" }
"ui.bufferline.active" = { fg = "white", bg = "background" }
"ui.bufferline.background" = { bg = "float_background" }

# Search
"ui.search" = { fg = "background", bg = "light_blue" }
"ui.search.current" = { fg = "white", bg = "red" }

# Selection
"ui.selection" = { bg = "surface2" }
"ui.selection.primary" = { bg = "surface1" }

# Cursorline
"ui.cursorline.primary" = { bg = "surface1" }
"ui.cursorline.secondary" = { bg = "surface1" }

# Virtual / Guides
"ui.virtual.ruler" = { fg = "surface2" }
"ui.virtual.indent-guide" = "surface2"
"ui.virtual.whitespace" = "surface2"

"ui.virtual.inlay-hint" = { fg = "surface2", bg = "background" }
"ui.virtual.inlay-hint.parameter" = { fg = "teal", bg = "background" }
"ui.virtual.inlay-hint.type" = { fg = "yellow", bg = "background" }

"ui.virtual.jump-label" = { fg = "red", modifiers = ["bold"] }

# Highlight in picker preview, etc.
"ui.highlight" = { fg = "white", bg = "surface1" }

# Debugging
"ui.debug.breakpoint" = { fg = "red" }
"ui.debug.active" = { fg = "yellow" }

############################################
# Palette
############################################
[palette]
background = "#2C2A2E"
float_background = "#29272B"
results_background = "#1F1D20"

surface0 = "#3D3A40"
surface1 = "#47444B"
surface2 = "#524E56"

purple = "#D499FF"
teal = "#94E2D5"
beige = "#F2CDCD"
maroon = "#EE5396"
light_blue = "#43D5EE"
sky = "#89DCEB"
orange = "#FC9867"
red = "#FF6188"
yellow = "#FFD966"
green = "#A8DC76"
blue = "#82A6ED"

static = "#FDAB67"    # Unused but safe to keep
macro = "#603717"     # Unused but safe to keep

magenta = "#B841AE"
pink = "#EA89A8"
white = "#E4E6E7"
