require("plugins.misc.autopairs")
require("plugins.misc.gitsigns")
require("plugins.misc.betterescape")
require("plugins.misc.bufdelete")
require("plugins.misc.modes")
require("plugins.misc.comment")
