ln -fs ~/dotfiles/nvim ~/.config
ln -fs ~/dotfiles/bat ~/.config
ln -fs ~/dotfiles/karabiner ~/.config
ln -fs ~/dotfiles/fish ~/.config
ln -fs ~/dotfiles/wezterm ~/.config
ln -fs ~/dotfiles/.hammerspoon ~/
ln -f ~/dotfiles/.ignore ~/
ln -f ~/dotfiles/.gitconfig ~/
ln -f ~/dotfiles/starship.toml ~/.config/starship.toml
