ln -fs ~/dotfiles/kitty ~/.config
ln -fs ~/dotfiles/nvim ~/.config
ln -fs ~/dotfiles/bat ~/.config
ln -fs ~/dotfiles/karabiner ~/.config
ln -fs ~/dotfiles/fish ~/.config
ln -fs ~/dotfiles/wezterm ~/.config
ln -f ~/dotfiles/zsh/.zshrc ~/
ln -f ~/dotfiles/.ignore ~/
ln -f ~/dotfiles/.gitconfig ~/
