#!/bin/bash
mkdir -p "$HOME/.config"

ln -fs ~/dotfiles/nvim ~/.config
ln -fs ~/dotfiles/wezterm ~/.config
ln -fs ~/dotfiles/fish ~/.config
ln -fs ~/dotfiles/bat ~/.config
ln -fs ~/dotfiles/aerospace ~/.config

ln -fs ~/dotfiles/starship.toml ~/.config
ln -fs ~/dotfiles/.ignore ~/.ignore
ln -fs ~/dotfiles/.gitconfig ~/.gitconfig

if [[ $(uname) == 'Darwin' ]]; then
    ln -fs ~/dotfiles/.hammerspoon ~/
fi
