local function bind(op, outer_opts)
	outer_opts = outer_opts or { noremap = true, silent = true }
	return function(lhs, rhs, opts)
		opts = vim.tbl_extend("force", outer_opts, opts or {})
		vim.keymap.set(op, lhs, rhs, opts)
	end
end

-- local nmap = bind("n", {noremap = false})
-- local xnoremap = bind("x")
local nnoremap = bind("n")
local vnoremap = bind("v")
local inoremap = bind("i")
local tnoremap = bind("t")
local action = require("lspsaga.codeaction")
--LSP
nnoremap("gd", function()
	require("lspsaga.definition").preview_definition()
end)
nnoremap("gf", function()
	vim.lsp.buf.format()
end)
nnoremap("gi", function()
	vim.lsp.buf.implementation()
end)
nnoremap("gt", function()
	vim.lsp.buf.type_definition()
end)
nnoremap("ga", function()
	action.code_action()
end)
nnoremap("K", function()
	require("lspsaga.hover").render_hover_doc()
end)
nnoremap("gr", function()
	require("lspsaga.rename").lsp_rename()
end)
nnoremap("gD", function()
	require("lspsaga.finder").lsp_finder()
end)
nnoremap("gj", function()
	require("lspsaga.diagnostic").goto_next()
end)
nnoremap("gk", function()
	require("lspsaga.diagnostic").goto_prev()
end)
nnoremap("gJ", function()
	require("lspsaga.diagnostic").goto_next({ severity = vim.diagnostic.severity.ERROR })
end)
nnoremap("gK", function()
	require("lspsaga.diagnostic").goto_prev({ severity = vim.diagnostic.severity.ERROR })
end)
nnoremap("ge", function()
	require("lspsaga.diagnostic").show_line_diagnostics()
end)
inoremap("gs", function()
	require("lspsaga.signaturehelp").signature_help()
end)
nnoremap("<C-j>", function()
	action.smart_scroll_with_saga(1)
end)
nnoremap("<C-k>", function()
	action.smart_scroll_with_saga(-1)
end)

--misc
inoremap("jj", "<Esc>")
inoremap("jk", "<Esc>")
inoremap("<S-Tab>", "<Esc>Ea")
inoremap("<S-CR>", "<Esc>o")

nnoremap("å", function()
	require("nvim-tree").toggle()
end)
nnoremap("Å", ":LSoutlineToggle<CR>")

nnoremap("L", "$")
nnoremap("H", "0")
vnoremap("L", "$")
vnoremap("H", "0")

nnoremap("<S-q>", function()
	require("bufdelete").bufdelete(0, true)
end)
nnoremap("<Tab>", ":bnext<CR>")
nnoremap("<S-Tab>", ":bprev<CR>")

nnoremap("<leader>ww", ":vsplit<CR>")
nnoremap("<leader>ws", ":split<CR>")
nnoremap("<leader>wq", ":q<CR>")
nnoremap("<leader>h", "<C-w>h")
nnoremap("<leader>j", "<C-w>j")
nnoremap("<leader>k", "<C-w>k")
nnoremap("<leader>l", "<C-w>l")

tnoremap("<Esc>", "<C-\\><C-n>")

--Telescope
nnoremap("<leader>fs", function()
	require("telescope.builtin").grep_string()
end)
nnoremap("<leader>ff", function()
	require("telescope.builtin").find_files()
end)

nnoremap("<leader>fl", function()
	require("telescope.builtin").live_grep()
end)

nnoremap("<leader>fw", function()
	require("telescope.builtin").current_buffer_fuzzy_find()
end)

nnoremap("<leader>fF", function()
	require("telescope").extensions.file_browser.file_browser()
end)
